# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Raghav Sethi
description:      ''
url:              http://raghavsethi.org

paginate:         5
paginate_path:    "/blog/page:num"
permalink: 		    "/blog/:categories/:year/:month/:day/:title"

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-feed
  - jekyll-paginate
  - redcarpet